#!/bin/sh

tmux new-session -d
tmux send-keys -t 0 "cd ~/neptune; vim" enter
tmux new-window
tmux split-window -v -p 10
tmux select-pane -t 0
tmux split-window -h -p 50
tmux send-keys -t 0 "cd ~/neptune/; docker-compose up" enter
tmux send-keys -t 1 "cd ~/neptune/" enter
tmux send-keys -t 2 "cd ~/neptune/" enter
tmux -2 attach-session -d
